### ISSUE TITLE
Add support for correlating metrics by setting SPRING_CLOUD_APPLICATION_GUID

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#126]

**Comment by markpollack** [comment]
See related issue on PCF here - https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/178 for details. It should be similar.

**Comment by trisberg** [comment]
do we need SPRING_APPLICATION_INDEX? We don't have an instance index for sources
