### ISSUE TITLE
Configuring multiple brokers and ZK nodes

### ISSUE THREAD

**Issue by balistof** [spring-cloud/spring-cloud-deployer-kubernetes#127]
how can I configure the deployer with multiple kafka brokers and zk nodes?

comma as seperator between kafka brokers and zk nodes is not working as there is already an outer comma seperator for multiple environment variables.

**Comment by balistof** [comment]
I figured it out using the array yaml format. Maybe this should be changed in the documentation.

**Comment by trisberg** [comment]
We don't have any docs for this project, could you point to the docs where you think this would be helpful?
