### ISSUE TITLE
Add support for assigning pods to nodes

### ISSUE THREAD

**Issue by RemonSinnema** [spring-cloud/spring-cloud-deployer-kubernetes#132]
See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/.

Use case: I'd like to divide my cluster into nodes that bear production load, and test nodes for e.g. performance tests.

**Comment by donovanmuller** [comment]
I have implemented the [`nodeSelector`](https://github.com/donovanmuller/spring-cloud-deployer-openshift/blob/master/src/main/java/org/springframework/cloud/deployer/spi/openshift/OpenShiftDeploymentPropertyKeys.java#L51) deployment property in the [OpenShift deployer](https://github.com/donovanmuller/spring-cloud-deployer-openshift). @RemonSinnema would this meet your requirements?

```java
/**
 * An optional nodeSelector to indicate where to schedule pods. All of the following are valid:
 * <code>spring.cloud.deployer.openshift.deployment.nodeSelector=region: primary,role:processor,label : something</code>
 * See https://docs.openshift.org/latest/dev_guide/deployments.html#assigning-pods-to-
 * specific-nodes
 */
String OPENSHIFT_DEPLOYMENT_NODE_SELECTOR = "spring.cloud.deployer.openshift.deployment.nodeSelector";
```

**Comment by RemonSinnema** [comment]
Yes, although support for node affinity would be good to have as well.

**Comment by donovanmuller** [comment]
@RemonSinnema just to confirm, is your requirement for [node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature) specifically or [Pod affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature) as well?

**Comment by RemonSinnema** [comment]
My use case us for node affinity only.

**Comment by trisberg** [comment]
I added a new issue for supporting `nodeSelector`: #147 

We'll keep this original one for the more involved Node affinity support

**Comment by trisberg** [comment]
See: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature

**Comment by sabbyanandan** [comment]
This was addressed in https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/bebd4addedaffe40a1f04fafcddeba3528c632e4.
