### ISSUE TITLE
Remove extra occurrences of org.json.JSONObject on the class path

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#142]
From the build:

```
Found multiple occurrences of org.json.JSONObject on the class path:

	jar:file:/Users/trisberg/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
	jar:file:/Users/trisberg/.m2/repository/org/json/json/20140107/json-20140107.jar!/org/json/JSONObject.class

You may wish to exclude one of them to ensure predictable runtime behaviour
```

**Comment by haoxuexiaoyao** [comment]
you can user `rm -rf /Users/trisberg/.m2/repository/com/vaadin/external/google/android-json/*`,This method can be solved.

**Comment by YShane** [comment]
I'm still hvaing this issue, unfortunately.

**Comment by knightofbatons** [comment]
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
edit pom.xml exclude one of them

**Comment by rliuzzi** [comment]
If you are dealing with a gradle project:

    testCompile("org.springframework.boot:spring-boot-starter-test"){
    	exclude group: "com.vaadin.external.google", module:"android-json"
    }

**Comment by neerajjain92** [comment]
My comment might be unrelated due to this issue but it can help someone facing the similar issue as me, I was facing [RestClient always gives “I/O reactor status: STOPPED”](https://discuss.elastic.co/t/restclient-always-gives-i-o-reactor-status-stopped/117534). With @knightofbatons fix my problem got resolved.

**Comment by tb-kubra** [comment]
> edit pom.xml exclude one of them

I also needed to exclude it from:
```
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-properties-migrator</artifactId>
</dependency>
```
