### ISSUE TITLE
Add deployment property for supplying service annotations

### ISSUE THREAD

**Issue by djgeary** [spring-cloud/spring-cloud-deployer-kubernetes#144]
We are using Spring Cloud Dataflow on Kubernetes on AWS, and we deploy streams with http sources.
Currently we can create a loadbalancer using the deployment property:
app.http.spring.cloud.deployer.kubernetes.createLoadBalancer=true
However this creates an external (internet facing) load balancer which is not what we want. 
We have other Spring Boot microservices in AWS but outside Kubernetes that we want to be able to communicate with http stream sources in Kubernetes via an internal load balancer.

Looking at (https://github.com/kubernetes/kubernetes/issues/16047) its possible to mark a loadbalancer on AWS as internal by passing 'service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0' as an annotation on service creation.

Would it be possible to update KubernetesAppDeployer to allow this functionality? I realise the annotation is beta and AWS specific so the best solution may be to support passing annotations in general as deployment properties on service creation and we can pass the one we need.

**Comment by trisberg** [comment]
Yes, passing annotations would be more general purpose.

I changed the title from _Support internal load balancers in kubernetes on AWS (or allow annotation deployment properties)_ to _Add deployment property for supplying service annotations_
