### ISSUE TITLE
Add support for adding nodeSelector

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#147]
`--spring.cloud.deployer.kubernetes.nodeSelector='disk:ssd,arch:amd64'`

**Comment by donovanmuller** [comment]
@trisberg `nodeSelector` has been implemented in the OpenShift deployer for some time.

See implementation [here](https://github.com/donovanmuller/spring-cloud-deployer-openshift/blob/7d8724324113a690dbb15d1b934d9564572a58ac/src/main/java/org/springframework/cloud/deployer/spi/openshift/resources/deploymentConfig/DeploymentConfigFactory.java#L120) using deployment property which looks like [`spring.cloud.deployer.openshift.deployment.nodeSelector=region: primary,role:processor,label:something`](https://github.com/donovanmuller/spring-cloud-deployer-openshift/blob/d395d676cc920882b87ba48447f8d9ad061ac6c2/src/main/java/org/springframework/cloud/deployer/spi/openshift/OpenShiftDeploymentPropertyKeys.java#L51)

Could perhaps serve as a reference point?

**Comment by trisberg** [comment]
Yep, thanks @donovanmuller, I was just starting to look at that.

**Comment by trisberg** [comment]
@donovanmuller do you mind taking a peek at https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/148

**Comment by markfisher** [comment]
side note: @donovanmuller it would be great if we could collaborate on a plan to move any generically applicable functionality from your implementation down to the k8s layer

**Comment by donovanmuller** [comment]
@trisberg LGTM 👍

@markfisher makes sense. I'll try check if there is any functionality that could be pulled up...

**Comment by trisberg** [comment]
Thanks @donovanmuller 

You were already listed as author on these classes so I assumed that it was OK to include some of your code ;) 

Thanks again for helping out!
