### ISSUE TITLE
Try using StatefulSets for the indexed apps

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#150]
See: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by dturanski** [comment]
Blocked by this https://github.com/fabric8io/kubernetes-client/issues/706

**Comment by dturanski** [comment]
Issue resolved. The api supports it but hard to find.

**Comment by dturanski** [comment]
https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/160

**Comment by mbogoevici** [comment]
I think it makes sense to support StatefulSets as a distinct deployment flavour regardless whether the applications are indexed or not (e.g. by adding a flag). Indexed apps can use StatefulSets by default. This could help supporting stateful applications (e.g. Kafka Streams) as part of the pipeline.
