### ISSUE TITLE
Add support for defining a side-car container

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#151]
Support side-car container for database access to Google Cloud SQL as well as Istio Service Mesh integration.

**Comment by dturanski** [comment]
Is the `spike` related to Google Cloud SQL and Istio integration or generally how to deploy a sidecar?

**Comment by trisberg** [comment]
I hope it would be applicable to any sidecar, Cloud SQL and Istio where to implementations that I was thinking of, but ideally it should be general so other sidecars can be applied as well. We should aim to support defining a sidecar with options for name, image/tag, command, volumeMounts, envVars and anything else that is needed.

**Comment by dturanski** [comment]
That was my interpretation too. I'm just wondering about the spike designation. So far it seems fairly straightforward. So far I can build a PodSpec with multiple containers defined by something like `spring.cloud.deployer.kubernetes.side-cars='{"side-car1": {"image": "dturanski/python-thingy:0.0.1"}, "env": {"GRPC_PORT": 9191}}'`.  Haven't tried deploying one yet...

**Comment by sabbyanandan** [comment]
Scope of this spike is complete via: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/156.
