### ISSUE TITLE
Investigate refactoring the way we launch tasks - use jobs

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#152]
Investigate refactoring the way how we launch tasks (R&D) -- pods vs. jobs

**Comment by trisberg** [comment]
Using a Job for launching tasks present a problem when the task exits with a non-zero exit code. The Job will restart a Pod or create a new pod depending on the `restartPolicy`. We can limit how long this goes on for by specifying  `activeDeadlineSeconds` combined with `restartPolicy: Never`. When that deadline is reached the Job will stop creating Pods and leave the failed ones so we can examine the logs. Each Pod's task execution will be entered in the TASK_EXECUTION table with the exit code and error message.

**Comment by trisberg** [comment]
To give us more we cloud create a Controller Pod that would launch the task once and then return 0 regardless of the task outcome.  

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#single-job-starts-controller-pod

**Comment by cppwfs** [comment]
While the controller-pod solution requires more work.  It matches what we are trying to do with tasks.  More importantly this will work with composed tasks, where the option above will not.

**Comment by mminella** [comment]
@trisberg "return 0"...I assume that means return 0 to the underlying K8s system (not impacting what the JVM or Spring Cloud Task does)?

**Comment by trisberg** [comment]
Yes, the task will be launched in a separate pod and can do it's thing, then the controller pod will just talk to the k8s system, this is transparent to the Spring Cloud Task operations.

**Comment by cppwfs** [comment]
correct.   The job monitors the controller pod which handles the task pod.  Our controller pod would always return zero regardless  the  task result.

**Comment by mminella** [comment]
I like it!
