### ISSUE TITLE
Create a Controller Pod for task launching

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-deployer-kubernetes#153]
To give us more controll we should create a Controller Pod that would launch the task once and then return 0 regardless of the task outcome.  

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#single-job-starts-controller-pod

See #152

**Comment by sabbyanandan** [comment]
We deploy tasks as "pods" by default; however, there's an option via `createJob` to launch the tasks as jobs instead.
