### ISSUE TITLE
How to add init-containers to pods part of stream pipeline

### ISSUE THREAD

**Issue by ravindrabhatt** [spring-cloud/spring-cloud-deployer-kubernetes#161]
I was looking into the the deployer codebase, is there a way we can configure initContainers for the pods that get deployed as part of stream pipeline.

**Comment by sabbyanandan** [comment]
Hi, @ravindrabhatt. In the `master` branch, by default for streams deployed with [partitioning characteristics](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java#L125), we apply [StatefulSets and Init Containers](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java#L357) - please have a look and let us know if that fits the need. If there's anything specific you're looking to do with what is already in place, a use-case description might be useful, too.
