### ISSUE TITLE
Investigate why "testMultipleInstancesDeploymentAndPartialState" leaves behind resources

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#166]
As a developer, I'd want to troubleshoot why `testMultipleInstancesDeploymentAndPartialState` is leaving behind unused resources after the test run. We see the following in the test-logs. This is consistently observed when running against minikube (1.8.2). 

> "Test named testMultipleInstancesDeploymentAndPartialState left behind an app for deploymentId 'app-aa9c98e5-ae8f-48c1', trying to cleanup"

**Comment by chrisjs** [comment]
im not seeing this when running the test locally nor in CI builds across k8s versions, maybe its been resolved over time.
