### ISSUE TITLE
Fix issue with empty storage request when creating stateful set

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-deployer-kubernetes#178]
Currently, the logic in deployer is looking for indexed property in the request and if finds one, it will create stateful set with empty storage request which hangs and does not create PVC in Kubernetes on AWS (i.e. EBS based storage) It seems to work fine in minikube thou.

**Comment by ilayaperumalg** [comment]
It looks like the positive integer check validation of PVC has recently been added (since v1.9.0-alpha.3): kubernetes/kubernetes@98e2c8c

**Comment by mv78** [comment]
actually we are on k8s 1.8 and it also checks for positive number in pvc

**Comment by ilayaperumalg** [comment]
@mv78 That's why it worked for you in minikube :-)

**Comment by mv78** [comment]
I guess you are right, the check was added in 1.9 however in aws, you can
provision zero sized ebs and it just stais pending and pods can bind to pvc
