### ISSUE TITLE
Deployer indexed property value is ignored for last app in the stream

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-deployer-kubernetes#179]
I have created simple stream definition:  time | log
I have tried passing deployer indexed property in number of ways and it still being ignored for last app (i.e. log)

1) deployer.time.indexed=false 
   deployer.log.indexed=false
2) deployer.*.indexed=false

The result is always 
Stream Deployment properties: {
  "log" : {
    "spring.cloud.deployer.indexed" : "true",
    "spring.cloud.deployer.group" : "teststream"
  },
  "time" : {
    "spring.cloud.deployer.indexed" : "false",
    "spring.cloud.deployer.group" : "teststream"
  }
}

**Comment by viniciusccarvalho** [comment]
This is going to be fixed once https://github.com/spring-cloud/spring-cloud-dataflow/pull/2043 is merged. Dataflow is currently forcing indexed to true on all non source apps, and hence why you see the sink having indexed set to true.

Closing as is already being addressed by https://github.com/spring-cloud/spring-cloud-dataflow/issues/1876
