### ISSUE TITLE
Add service discovery support for K8S services

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#18]
As a developer, I'd like to leverage a service discovery mechanism that is native to k8s platform, so I can discover relevant services such as binder, datasource, analytics store etc. 

https://github.com/fabric8io/spring-cloud-kubernetes

**Comment by trisberg** [comment]
With the option of setting env vars per deployment we should have everything needed for this. Any starter app can be rebuilt with fabric8 spring-cloud-kubernetes support for ConfigMap and Secrets.
