### ISSUE TITLE
Support configuring ingress

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-deployer-kubernetes#184]
Especially in skipper when upgrading app version you i.e. need to define a new node port which makes its usage rather cumbersome. If we could skip that step(defining actual port) and route traffic automatically via ingress, we'd get nice user level predictable addresses. Also it might allow better upgrade strategies on k8s.

**Comment by to-wi** [comment]
I think this relates to #370 
From my experience most users want to expose a deployed stream via an Ingress. Therefore either a stable service name or an automatic Ingress creation is required

**Comment by chrisjs** [comment]
the service name which gets built from the info passed from skipper needs to be consistent and then this would be possible. see: https://github.com/spring-cloud/spring-cloud-skipper/issues/953
