### ISSUE TITLE
Revisit the "undeploy" implementation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#193]
Specifically, we want to [review](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/587aca8b6c88a97e20c9376e586c78f84ad96a60/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java#L177-L194) why are we waiting and why the exception is not handled correctly.

**Comment by chrisjs** [comment]
@sabbyanandan i think we can close this issue in favor of #195
