### ISSUE TITLE
Add doc for using service/pod annotations as deployer properties

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-kubernetes#205]
As part of https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/198, we have support to add pod annotations as deployer properties. We already have support for service annotations as deployer properties as well. 

We need to update doc how one can make use of this.

**Comment by chrisjs** [comment]
Same will go for https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/204 so ill do a round of doc updates for the annotation types at once

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#274
