### ISSUE TITLE
Document entry point styles

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-deployer-kubernetes#211]
We have 3 different `entryPointStyle` options available: `exec`, `boot`, and `shell`. Usage of these needs to be documented. Some verification should be done around the `SPRING_APPLICATION_JSON` check in DefaultContainerFactory.create(..) in terms of being able to define this variable in a deployment manifest as well as on a per app basis at the same time.

**Comment by sabbyanandan** [comment]
This issue was moved to spring-cloud/spring-cloud-dataflow-server-kubernetes#281
