### ISSUE TITLE
Cant pass pod annotations that contain multiple colon ":" in the value

### ISSUE THREAD

**Issue by mv78** [spring-cloud/spring-cloud-deployer-kubernetes#226]
Currently we can use property "deployer.kinesis-sink.kubernetes.podAnnotations=iam.amazonaws.com/role:arn:aws:iam::12345678:role/role-name" to pass pod spec annotations. We use this to pass AWS role ARN "arn:aws:iam::12345678:role/role-name"
Due to get annotation code in deployer that looks if split annotation pares have 2 values by splitting using ":". This fails since we have more than one colon in the value.

**Comment by alvgarvilla** [comment]
Hi @chrisjs and @sabbyanandan I had to fix this issue for my job. I've created a pull request https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/234

**Comment by sabbyanandan** [comment]
Nice! Thanks, @alvgarvilla. We will have a look soon.

**Comment by chrisjs** [comment]
merged in 90888d and d00b97
