### ISSUE TITLE
Conditionally create a KubernetesAppDeployer in auto-configuration

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud/spring-cloud-deployer-kubernetes#227]
The creation of a `KubernetesAppDeployer` bean in [`KubernetesAutoConfiguration`](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAutoConfiguration.java) is unconditional: 

```
	@Bean
	public AppDeployer appDeployer(KubernetesClient kubernetesClient,
	                               ContainerFactory containerFactory) {
		return new KubernetesAppDeployer(properties, kubernetesClient, containerFactory);
	}
```

This makes it difficult for an application to include this Deployer project in the same app as other Deployer projects and choose the Deployer implementation at runtime (e.g. with Spring profiles). 

Creation of the `KubernetesAppDeployer` bean could be qualified with `@ConditionalOnMissingBean(AppDeployer.class)` as is done in the [Cloud Foundry Deployer auto-configuration](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/deployer/spi/cloudfoundry/CloudFoundryDeployerAutoConfiguration.java#L94) to give applications more control over application configuration.

**Comment by chrisjs** [comment]
additionally looks like local server does the same https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerAutoConfiguration.java#L39 so seems reasonable to keep in sync
