### ISSUE TITLE
Add support to define security model for the deployable pods

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#232]
As a user, I'm attempting to deploy a "secured" Boot App (actuator endpoints are secured); however, it fails to deploy due to the default liveness/readiness checks on HTTP instead of HTTPS.

More details in the [gitter thread](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b10320152e35117cdf87363).

A few options to explore:
- [ ]  configure health-checks to be on a "port" instead of http endpoint
- [ ] pass the encoded user/pass creds in the HTTP header (in Fabric8 client) while invoking the deployment target 
- [ ] consider an option to toggle between security models as property overrides

**Comment by chrisjs** [comment]
since it sounds like the recent reports are due to end points secured by default in boot 2 (?) we could probably just support basic auth for that to work and see how things shake out. might want to wait for other auth methods and checking based on port if we get requests for them.

**Comment by chrisjs** [comment]
issue for implementation at #236
