### ISSUE TITLE
Support pod annotations for tasks created by KubernetesTaskLauncher

### ISSUE THREAD

**Issue by alvgarvilla** [spring-cloud/spring-cloud-deployer-kubernetes#235]
Similar to https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/204, but add pod annotations when creating the tasks. Currently we have to define the values SPRING_CLOUD_DEPLOYER_KUBERNETES_JOB_ANNOTATIONS regardless whether it is a JOB or a POD. I think it should be called SPRING_CLOUD_DEPLOYER_KUBERNETES_POD_ANNOTATIONS instead.

I got it fixed for my job and I will create a pull request in case it is accepted.

**Comment by chrisjs** [comment]
the value of property `spring.cloud.deployer.kubernetes.jobAnnotations` is applied to either the underlying `Job` or `Pod` thats created when a task is launched depending on the conditional: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java#L99

agreed, the naming could probably be better say but maybe say `task annotations` as the task is launched as either a job or pod. if you have a PR that would deprecate `jobAnnotations` and introduce `taskAnnotations` (both should still work) id be happy to take a look

**Comment by alvgarvilla** [comment]
Hi @chrisjs , sorry for the delay. I agree, tasks annotations is more accurate.

I found another "issue" (I do not call it issue because it is k8s expected behaviour). When adding annotations to jobs, we do not add them to the pod the job creates. This is quite important for people that wants to use projects like kiam, which uses the annotations of the pod for assuming IAM roles. It is an easy fix and, since it is related to annotations as well, I will create a PR with both changes.

**Comment by sabbyanandan** [comment]
Hi, @alvgarvilla. A friendly follow-up. Feel free to start the dialog with a PR - we would love to collaborate to get it included in the next release.

**Comment by kristoflemmens** [comment]
Hi, we have the same problem. If we use create-job than the job annotations are only on the job not on the pod. I created a PR for this https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/pull/377

**Comment by chrisjs** [comment]
pr merged in 3a8a61b2e18bb0bcb6a17ee7677c5f8165f6c396
