### ISSUE TITLE
Add a property to expose container ports

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#240]
As a user, I'm attempting to deploy a stream with the OOTB `websocket-sink`. To connect to the sink from an external application, I'd have to gain access to the container's port and I don't have a direct way to do it. 

I work around it with `port-forward` option (eg: `k port-forward foooooz-websocket-v1-69948bf749-qnpfz 9292:9292`).

**Acceptance:**
- Add a `exposeContainerPorts` as a configurable option
- Setting this would automaically configure the pod-container to port forward to the configured port
- Document the use of it in SCDF

**Comment by chrisjs** [comment]
closing this for now as in the use case we had we created a LB as we needed the IP beforehand anyway
