### ISSUE TITLE
Better pod naming convention 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-kubernetes#252]
_From @ilayaperumalg on October 29, 2018 6:54_

_From @siddhantsorann on October 29, 2018 6:23_

For the batch jobs, there should be easier ways to look at the logs. For which in the kuberenets server if there is a better pod naming convention which might include things like execution ID, it might become easier to find the particular pod related to the task execution. 

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2522_

_Copied from original issue: spring-cloud/spring-cloud-dataflow-server-kubernetes#348_

**Comment by sabbyanandan** [comment]
We do not have a flexible naming strategy that can alter the deployment units on K8s. Even if we did, it'd be complex to handle internally to support for both streams/tasks. This is outside the scope of deployer+scdf.

There are richer metrics/monitoring support in SCDF 2.3, which could be useful to drill into stream/task-specific issues from the Dashboard directly.
