### ISSUE TITLE
Deprecation cleanup

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-deployer-kubernetes#259]
Given the 2.0 bump, this is probably a good time to remove any deprecated methods. Also, ensure any reference documentation, AT's etc are updated.

**Comment by chrisjs** [comment]
@sabbyanandan changes should be minimal, good to slot in somewhere on the 2.0 release path?

**Comment by sabbyanandan** [comment]
Yes, let's please do it.

**Comment by chrisjs** [comment]
* doc updates are covered in PR: https://github.com/spring-cloud/spring-cloud-dataflow/pull/2748 - specifically commit: https://github.com/spring-cloud/spring-cloud-dataflow/pull/2748/commits/801faa8d9bbcf3c2a6c267660e3ebb4aa6051536

* AT changes are in commit: https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/commit/81cf8e7d743b9305b6fcf979b96acb05142e6edc
