### ISSUE TITLE
Add secretKeyRef to the container for passing secrets to the streams/tasks

### ISSUE THREAD

**Issue by alvgarvilla** [spring-cloud/spring-cloud-deployer-kubernetes#264]
Currently we can pass environment variables to the tasks created but not as secret. In order to not expose sensible information, we should be able to support "secretKeyRef" as described in here https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by sabbyanandan** [comment]
My apologies for the delay, @alvgarvilla. We are planning to experiment with a native as well as a solution involving `spring-cloud-kubernetes`. Once when we have a SNAPSHOT build including the support, it'd be great if you can try it out and validate it for us.

**Comment by alvgarvilla** [comment]
Great @sabbyanandan ! good to know!
