### ISSUE TITLE
Add Support for Tolerations

### ISSUE THREAD

**Issue by JStrittmatter** [spring-cloud/spring-cloud-deployer-kubernetes#265]
When deploying to kubernetes there should be an ability to add the tolerations to the deployments so that proper controls can be used.

**Comment by sabbyanandan** [comment]
It seems like spring-cloud/spring-cloud-deployer-kubernetes#266 (thank you for the PR!) relates to this issue, so I'm reopening and associating the both to track it in waffle board.

**Comment by sabbyanandan** [comment]
@JStrittmatter: Just curious. Could you describe how you intend to use this in the deployer? Maybe also using SCDF to apply this when deploying streams/tasks? 

Few lines about the use-case would help relate to inflight changes.

**Comment by JStrittmatter** [comment]
We are currently looking to use it in skipper from SCDF to deploy out to kubernetes.  This is to support taints to control which nodes that the pods are deployed to.  Here is the kubernetes documentation on this feature:

https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

In our case we have a specific namespace and specific nodes that we are wanting all of these deployments to happen on so that they do not cause resource issues for other applications from within the cluster.  Let me know if you have further questions.

Thanks
