### ISSUE TITLE
Add support for TCP and command liveness probes

### ISSUE THREAD

**Issue by hgeraldino** [spring-cloud/spring-cloud-deployer-kubernetes#299]
Spring-boot applications that don't serve traffic via HTTP (e.g. gRPC server) can't be deployed via spring-cloud-deployer-kubernetes because the only supported probes are HTTP.

I'd like to extend support for liveness/readiness probes and include support for command and TCP liveness probes. The current implementation where probes are defaulted to HTTP should be kept for backward compatibility, and a new model should be introduced to support the other  probe types.

**Comment by sabbyanandan** [comment]
Hi, @hgeraldino. It is a reasonable addition to be able to switch between HTTP vs. TCP ports for probes. 

Please feel free to start a PR - we could collaborate.

**Comment by chrisjs** [comment]
2.7.0.m1 is already out, should that be something else?

**Comment by sabbyanandan** [comment]
That's just an iteration label; we will include it in RC1.
