### ISSUE TITLE
Supports use of images other than busybox in KubernetesAppDeployer

### ISSUE THREAD

**Issue by benelog** [spring-cloud/spring-cloud-deployer-kubernetes#315]
I am trying to use Spring Cloud Data Flow on internal installation of K8S in our company.

Unforunately, I cannot use the 'busybox' image according to the security policy of our company.
The security team provides white list of base images permitted to use in the internal K8S cluster.

'busyboyx' is hard coded in [KubernetesAppDeployer.java](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java#L440)

If it is possible to specify other image name, it will be very helpful for us.

**Comment by sabbyanandan** [comment]
Hi, @benelog. I can see this as a useful area for customization - precisely for the reason that you listed. If you want to take a crack at it, feel free to start a PR, and we can collaborate with you.

**Comment by benelog** [comment]
@sabbyanandan 
Thank you for your positive consideration.
I'll try to contribute.
