### ISSUE TITLE
Fix configuration properties with kebab-case 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-kubernetes#328]
With Spring Boot 2.x supporting the kebab-case (ex: my-property-key) only if the `@ConfigurationProperties` is annotated with a prefix in kebab-case or in the `application.properties`, we start to some of the properties such as the deployer/app properties properties are not applied correctly to the target platform.

For instance, from the SCDF UI, we show the deployer properties with the kebab-case (ex: pod-annotations) and once user configures these properties (ex: deployer.<myapp>.kubernetes.pod-annotations=key:value), this deployer property doesn't get applied at all.

We need to:

 - Fix the places wherever the kebab-case properties are omitted
 - Update the documentation to replace the existing kebab-case properties

**Comment by chrisjs** [comment]
as it stands, pretty sure 100% of deployment properties that are plucked out of the deployment properties map are not in "kebab-case". how properties as a whole should likely be reviewed/revamped as there are many variations on how they are mapped. some are mapped into boot configprops on server start up, or that class is used as a binding for more complex objects, plucking app specific things out of deployment properties map, etc. also there are some precedence rules between "global" and "app" specific properties. 

so a bit to think about when the time comes.
