### ISSUE TITLE
Expose Job specific Kubernetes Properties in Deployer

### ISSUE THREAD

**Issue by janamailzuu** [spring-cloud/spring-cloud-deployer-kubernetes#337]
Currently there is no way to cleanup the pods and Jobs created by the Spring Cloud Tasks automatically.  

Based on the below documentation, we could see there are configs available for Jobs to cleanup the finished Jobs and pods automatically. 
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

_**Useful configs for Jobs cleanup:**_

1.  **.spec.ttlSecondsAfterFinished**    - Useful for specifying the time to live seconds for Jobs after it is finished.
2. **.spec.backoffLimit** - useful for specify the number of retries before considering a Job as failed. Default backoff Limit is 6.Addition of this property will help us set the limit to 1 or 2 at the max.
3. **.spec.template.spec.restartPolicy** - useful for specifying the restart policy. default seem to be "Always". Addition of this property will help us set the restart policy to "Never"

These configs are not currently exposed in deployer as per the below documentation.
https://docs.spring.io/spring-cloud-dataflow/docs/2.2.1.RELEASE/reference/htmlsingle/#configuration-kubernetes-deployer

Since there is no way to cleanup the pods and Jobs created automatically, Exposing these properties will really benefit everyone.

**Comment by chrisjs** [comment]
test with istio sidecar injection - when job is complete the sidecar keeps running. ensure all is cleaned up

**Comment by ilayaperumalg** [comment]
I believe this is also related to #332

**Comment by chrisjs** [comment]
yes; similar with more or less the same content -- should probably be grouped together and done at the same time

**Comment by gurugubelli** [comment]
ttlSecondsAfterFinished not supported yet
