### ISSUE TITLE
Can not deploy a stream in kubernetes without the -v{n} suffix

### ISSUE THREAD

**Issue by xetra11** [spring-cloud/spring-cloud-deployer-kubernetes#340]
When deploying a Stream with a Source it happens that for every redeployment of the Stream the name has the suffix `my-stream-v12` for instance. I need the name without this suffix but can not find a way to deactivate this feature.

I feel that it worked before but now it doesn't. No option to get rid of the suffix.

**Comment by ilayaperumalg** [comment]
Hi @xetra11 , I assume you are deploying the stream applications using Spring Cloud Data Flow and Spring Cloud Skipper. The Skipper adds this suffix for version management of individual applications inside the stream and it is mandatory.

**Comment by ilayaperumalg** [comment]
If you are keen on understanding where this is done, you can check [this](https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeploymentRequestFactory.java#L96) place at the Spring Cloud Skipper codebase.

**Comment by chrisjs** [comment]
closing per skipper comments above, not deployer related
