### ISSUE TITLE
Add deploymentLabels as a deployer property

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-kubernetes#344]
As part of #248, the `spring.cloud.deployer.kubernetes.deploymentLabels` property is checked by the K8s app deployer for additional labels. But, this specific property wasn't added into K8s deployer properties.

**Comment by chrisjs** [comment]
“wasn’t added into k8s deployer properties” as in meaning exposed as a global property or something else? global/per app is considered on a per property basis

**Comment by kingofmooks** [comment]
I also am having trouble with using this one.. it doesn't recognise this as a valid property 

![image](https://user-images.githubusercontent.com/61328202/75060044-03b2b780-54d6-11ea-82fe-0e761802e20d.png)

I've also tried adding ```deployer.task-launcher-dataflow.deploymentLabels=myLabelName:myLabelValue```

for the stream definition as well, but it doesn't seem to be reflected in kubernetes..  but i'm not sure i'm using that right.

Data flow Version 2.1.2.RELEASE

**Comment by onobc** [comment]
This was completed in https://github.com/spring-cloud/spring-cloud-deployer/commit/52bd1ee6e483b9dfacab9af5f48b7a00ee0921b2#diff-cbc0099be796a4520bb4e90ca1f3f2f60d69fe6dff36eb3df19805eb1ccaaabdR616
