### ISSUE TITLE
Update K8s version compatibility matrix in the README

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-deployer-kubernetes#349]
The matrix in the [README](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes#kubernetes-compatibility) is dated. 

1) We run the SCDF's K8s ATs on 1.11, 1.12, and 1.13 .. in GKE and PKS.

2) We also run the K8s deployer ITs on K8s 1.11, 1.12, and 1.13.

So, let's remove all the old + stale k8s versions from the matrix, and list only the ones that are actively being tested.

Suggestion:
- List K8s-deployer 1.3.x, 2.0.x. 2.1.x as rows (3 rows)
- List K8s 1.11, 1.12, and 1.13 as columns (3 columns)

The matrix in the [Microsite](https://dataflow.spring.io/docs/installation/kubernetes/compatibility/#kubernetes-compatibility), however, is _almost_ in good shape. Almost because it needs an SCDF 2.3.x + K8s-deployer 2.1.x row.

**Comment by chrisjs** [comment]
microsite addressed in https://github.com/spring-io/dataflow.spring.io/commit/0b1cf44cbddee29c1d10986534d2c165987a0bce
