### ISSUE TITLE
initContainer doesnt support volumes nor mounts

### ISSUE THREAD

**Issue by isha1kh** [spring-cloud/spring-cloud-deployer-kubernetes#357]
I have an initContainer, where in am trying to install a certificate via volume and volumeMounts something like:

`{containerName: 'myinit', imageName: 'openjdk:jdk-oracle', commands: ['sh', '-c', 'cp /jvm/secret/certs /certificate/truststore.jks && keytool -import -alias rootCert -keystore /certificate/truststore.jks -trustcacerts -file /mypathto/secret/RootCertificate.crt'],volumeMounts: [{name: 'cert-secret', mountPath: '/cert/secret'}],volumes: [{name: 'cert-secret', secret: { secretName: 'certsecret' }}]}`

However although the initContainer is created the volumes and volumeMounts are never created thereby failing my command.

Looking at the code (https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/2f2b701e8d3e205a3e9c23a67ff1e28d197c4610/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesDeployerProperties.java#L307) it doesn't seem like init container supports volume/mounts yet, unless I've missed something.

Therefore wondering if there is any plan to add this support ?

**Comment by chrisjs** [comment]
theres no current feature request for it, so will use this as such. do feel free to contribute if you can
