### ISSUE TITLE
Add Jobs History Limits Policy for the Task jobs/pods

### ISSUE THREAD

**Issue by janamailzuu** [spring-cloud/spring-cloud-deployer-kubernetes#363]
Currently, There is no way to clean up the task pod/jobs regardless of the way it is getting launched(launching manually from dashboard or by schedule).

 Kubernetes CronJob specific default properties [Jobs History Limits](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits) will 
 be useful to specify how many completed and failed jobs should be kept .

When we tested the task scheduling with 2.3.0.RELEASE, Only the scheduler-task-launcher jobs are getting removed via this policy.However the task jobs/pod are not getting cleaned up and that is because the CronJob limits will only apply to the jobs it creates.

Please add this policy for the task pod/jobs. 

And also Please consider adding a generic property to delete the task pods after successful task run(when launched directly from the Task).

**Comment by chrisjs** [comment]
the new lingering pods will be cleaned up as part of #3793
