### ISSUE TITLE
ConfigMap Environment Variable are missing in Task Pod(SCDF-2.0.1.RELEASE) in Kubernetes

### ISSUE THREAD

**Issue by sachinpanhale** [spring-cloud/spring-cloud-deployer-kubernetes#369]
Issue Details :

We are using spring-cloud-dataflow-server-2.0.1 to deploy task using SCDF UI in Kubernetes environment but after launching the task application using LaunchTask option,the environment variables defined in the ConfigMap are not getting added to the task pod created in the Kubenetes environment.

The new task pod created successfully with default arguments(task name,datasource..etc) and environment(SPRING_CLOUD_APPLICATION_GUID) properties but it is missing the custom properties defined as a environment variables in the ConfigMap.

Added below configuration in scdf server deployment yaml file to map ConfigMap(scdf-sserver) to the data flow server.

 - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
          value: scdf-server

ConFigMap Environment varriable configuration:

spring:
  cloud:
    deployer:
      kubernetes: 
        environmentVariables:
'staging_mysql_datasource_username=root,staging_mysql_datasource_password=root,file_directory=/nfs/data'

We tested the same task application in spring-cloud-dataflow-server-1.7.0 version and in that it is working fine.All environment variables defined in ConfigMap are added to the task pod.

Is this known issue in version spring-cloud-dataflow-server-2.0.1?

Any help is greatly appreciated!

**Comment by chrisjs** [comment]
a lot changed from 1.x to 2.x, some of those being how things are configured with the merging of individual servers. also, 2.4 is the latest line, so if your upgrading from 1.7 that would likely be where you want to go.

for reference, you should ensure your configs when moving to the 2.x line look similar to for example those in:

https://github.com/spring-cloud/spring-cloud-dataflow/tree/2.4.x/src/kubernetes
