### ISSUE TITLE
Skipper doesnt pass deploymentLabels to Pods when deployerCount is more than 1

### ISSUE THREAD

**Issue by respondsid** [spring-cloud/spring-cloud-deployer-kubernetes#378]
I can see that deploymentLabels are present in the manifest and I passed them from properties editor. The spring consist of 1 source(1 instance) 2 processor (Each 4 instances) and one sink.

I passed in deploymenyLabels using deployer.<APP_NAME>.kubernetes.deploymentLabels for all 4 apps using properties editor, however when i describe prod i cannot see them passed in for the processor(Multiple instances), I can see them for source and sink (single instance)

"apiVersion": "skipper.spring.io/v1"
"kind": "SpringCloudDeployerApplication"
"metadata":
  "name": "sp-tika"
"spec":
  "resource": "docker:docker.fmr.com/fmr-ap127003/sharepoint-tika-processor"
  "resourceMetadata": "docker:docker.fmr.com/fmr-ap127003/sharepoint-tika-processor:jar:metadata:71"
  "version": "71"
  "applicationProperties":
    "spring.cloud.dataflow.stream.app.label": "test-app"
    "spring.cloud.stream.bindings.input.consumer.concurrency": "5"
   .
   .
  "deploymentProperties":
    "spring.cloud.deployer.indexed": "true"
    "spring.cloud.deployer.kubernetes.environment-variables": "profile=qa"
    "spring.cloud.deployer.count": "4"
    "spring.cloud.deployer.kubernetes.deploymentLabels": "foo:bar,foo1:bar1"
    "spring.cloud.deployer.group": "test-dev"

I looked at the AppDeployer code at 

https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesAppDeployer.java

 looks like, for indexed deloyment it doesnt execute deploymentLabel logic

	@Override
	public String deploy(AppDeploymentRequest request) {
                     .....
			if (indexed) {
				logger.debug(String.format("Creating Service: %s on %d with", appId, externalPort));
				createService(appId, request, idMap, externalPort);

				logger.debug(String.format("Creating StatefulSet: %s", appId));
				createStatefulSet(appId, request, idMap, externalPort);
			}
			else {
				logger.debug(String.format("Creating Service: %s on %d", appId, externalPort));
				createService(appId, request, idMap, externalPort);

				logger.debug(String.format("Creating Deployment: %s", appId));
				createDeployment(appId, request, idMap, externalPort);
			}

			return appId;
		...
	}

The deploymentLabels should get copied over as Metadata labels in stateful set. Any suggestions  ?

**Comment by ilayaperumalg** [comment]
Hi @respondsid , Thanks for reporting this and the investigation on the issue as well :-)

The Kubernetes deployer property `deploymentLabels` is meant to be applied to `Deployment` spec and currently not applied to `StatefulSet` (the StatefulSet is used when the application instances are indexed - to support partitioning etc.,).

Given this, the current `StatefulSet` is expected to support a way to pass the `labels` via deployment properties. Hence, we'll consider this as a feature request and scope it soon.

Thanks again!

**Comment by ilayaperumalg** [comment]
I think we can go with the following options:

- Add a new deployer property `statefulSetLabels` similar to `deploymentLabels` but the downside is that, the user is expected to understand the difference between using `statefulSetLabels` and `deploymentSetLabels` (partitoned stream vs non-partitioned stream apps). 
- Or, use the existing `deploymentLabels` property and set it for `StatefulSet` created for the partitioned stream application. This might also bring confusion as `deploymentLabels` are applied `StatefulSet` labels.

**Comment by chrisjs** [comment]
i think option 2 would be the most straightforward and we just update the docs `5.1.10. Deployment Labels` accordingly

**Comment by respondsid** [comment]
This is exaclty what i did reuse existing deploymentLabels property can we
speak or talk ?

**Comment by respondsid** [comment]
@ilayaperumalg  can you assign it to me ?
