### ISSUE TITLE
Merging of deployer and scheduler properties at the global level

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-deployer-kubernetes#389]
When setting properties at the server config account level, those properties get populated into `KubernetesDeployerProperties`. This works fine for tasks, streams, etc. When scheduling a task, properties are put into `KubernetesSchedulerProperties` which will work fine with deployment properties, but those specified at the server config account level do not get carried over.

**Comment by chrisjs** [comment]
also related to https://github.com/spring-cloud/spring-cloud-dataflow/issues/3985 in the scheduler case

**Comment by ilayaperumalg** [comment]
@chrisjs @cppwfs Upon investigation, I noticed that the merging of task platform properties into scheduler properties and then the appropriate cronjob/pod templates work fine except some of the explicit properties. The metadata `jobAnnotations` is one such case. I went ahead and pushed the changes in the PR and also added some test cases to demonstrate this working. Let me know if you see any issues with the other properties. I think we need to go case by case like adding annotations in this PR.

Also, when setting up the SCDF server level properties, it is not expected from the user to specify anything as `spring.cloud.scheduler` prefix instead all the properties would go under task platform properties and they get applied to both `deployer` and `scheduler` properties.

**Comment by chrisjs** [comment]
merged, yea looks like some prior changes for prop copying made things happy. adding "new" things like `jobAnnotations` to a particular object as in your PR is expected as that's more of a "feature add" scenario than the copying of deployer/scheduler props.

#3985 should be resolved by one more change @cppwfs and i discussed earlier

**Comment by ilayaperumalg** [comment]
This needs to be back ported into 2.4.x

**Comment by ilayaperumalg** [comment]
Back ported the changes into 2.4.x as 770a81d
