### ISSUE TITLE
Allow for better extensibility

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-deployer-kubernetes#39]
In the context of [this post](http://blog.switchbit.io/spring-cloud-deployer-openshift), it would be good if the access for methods in [`AbstractKubernetesDeployer `](https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/master/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/AbstractKubernetesDeployer.java) be relaxed to allow for extension.

Other common methods/functionality should also be extract into reusable methods.

**Comment by trisberg** [comment]
Will address client versions here: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/41
