### ISSUE TITLE
Unable to create a pod with "resources: limits" such as "nvidia.com/gpu: 1"

### ISSUE THREAD

**Issue by simonbrommers** [spring-cloud/spring-cloud-deployer-kubernetes#401]
At present, the only limits that seem to be able to be applied to created pods are cpu and memory.  Many cases could benefit from being able to specify other types of limits, e.g. nvidia.com/gpu

**Comment by chrisjs** [comment]
functionality is added to the project based on need/requests/submissions/ etc. if you have a particular request please update the issue for the specific part of functionality / use-case. the existing description of "able to specific other types of limits, e.g." is a bit open ended. also, contributions are always welcome so do feel free to make a PR if inclined.

**Comment by simonbrommers** [comment]
Thanks @chrisjs for the suggestion to make my issue more specific.
My project requires the ability to run pods that make use of GPU resources, where we have 1 GPU resource per node (non-sharable).  I have the ability to launch a pod directly within kubectl using the likes of:

`
    spec:
      containers:
      - name: nvidia-pipeline
        image: *********
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
`

I require the ability to be able to specify this kind of resource limits when using Spring Cloud Data Flow (either via the .yaml files for deployment or runtime properties).  So far I've looked into making the change, and found method deduceResourceLimits() in class DeploymentPropertiesResolver which is limited to only working with limits.cpu and limits.memory properties, but don't really understand the rest of the framework enough to be able to make the change without the worry of breaking things for others

**Comment by chrisjs** [comment]
thanks for the clarification. that method will look at deployment properties and build a structure which would be used downstream to send that info off to the underlying k8s client lib. similar to the existing cpu/memory, another limit attribute could be added for gpu's in a similar way, possibly structuring that particular resource in a somewhat generic way given nvida and amd gpu's are currently supported with their own name.

**Comment by simonbrommers** [comment]
I was thinking along exactly those lines @chrisjs .  I've got a plan on what code I'd like to change to make this happen.  I'm just struggling at present to be able to build this project and the docker image to test out the changes I want to put in.  Is there a guide to setting up a local development environment in which I can do this change, esp for building the docker image?

**Comment by chrisjs** [comment]
the deployer doesn't need a docker image made to test, that's generally done in the deployer test suite. are you referring to building  dataflow and skipper with the deployer changes and the corresponding image to test end to end?

**Comment by simonbrommers** [comment]
If there was however a nice simple way of creating the corresponding image for end to end testing that would make my life a lot simpler.

**Comment by simonbrommers** [comment]
This is brilliant help Chris - thanks so much - it'll help greatly.

Cheers

Simon
