### ISSUE TITLE
Need to find alternatives of docker container because kubernetes v 1.20.0

### ISSUE THREAD

**Issue by iceflower** [spring-cloud/spring-cloud-deployer-kubernetes#411]
kubernetes has informed us in the release notes of github that version 1.20.0 does not support the Docker Container. [release note v.1.20.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md), [deprecations of v.1.20.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation)

So, I'd like to know if the `Spring Cloud Deployer kubernetes`  development team can support other Container technologies that can replace the Docker Container.

**Comment by chrisjs** [comment]
its not "Docker containers" its usage of "Docker" by k8s itself. no changes are expected in deployer.

the following post goes more in-depth: https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/
