### ISSUE TITLE
seccompProfile under podSecurityContext does not work

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-deployer-kubernetes#412]
@TimoSchaz commented on [Thu Jan 21 2021](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4340)

I tried to apply seccompProfile under podSecurityContext for Tasks and Streams that should be deployed via SCDF Server and Skipper ,but it seems that they are not used.
Is it possible to set the Profile there ?
I think this is an important feature that should be supportet to provide better security.

I configured it as follows but its not working:

data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            platform:
              kubernetes:
                accounts:
                  default:
                    podSecurityContext:
                      seccompProfile:
                            type: Localhost
                            localhostProfile: profile.json

---

@ilayaperumalg commented on [Thu Jan 21 2021](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4340#issuecomment-764556710)

Hi @TimoSchaz , Thanks for reporting!

Yes, `seccompProfile` is not supported and we can look at supporting in the upcoming release.
If you would like to contribute, please submit a PR and we'd happy to help you clarify any questions you may have.

I am also moving this to `spring-cloud-deployer-kubernetes` as this issue belongs there.

**Comment by TimoSchaz** [comment]
Thank you for the fast feedback.
Another thing that also seems to be not implemented yet is the support for securityContext
as follows

 securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

To be able to make the started tasks and streams filesystems readonly this is needed.

Is this possible at the moment?
If not i think allowPrivilegeEscalation: false and readOnlyRootFilesystem: true should be implemented, because they are important security features.

**Comment by ilayaperumalg** [comment]
@TimoSchaz Sure, please go ahead and submit a PR to accommodate these properties. We'd be happy to help if you have any questions.
