### ISSUE TITLE
Configured podAnnotations are not applied for statefulSets

### ISSUE THREAD

**Issue by chringwer** [spring-cloud/spring-cloud-deployer-kubernetes#419]
If the deployment properties contain `podAnnotations`, those should be applied to statefulSets as well as they are for normal deployments.

**Comment by ilayaperumalg** [comment]
Hi @chringwer , Thanks for reporting this and yes, the `podAnnotations` aren't applied to StatefulSet (when the stream is partitioned). We'll have this addressed it soon.
