### ISSUE TITLE
Executing a shell command

### ISSUE THREAD

**Issue by canerkoseren** [spring-cloud/spring-cloud-deployer-kubernetes#439]
Hi all,

I am triggering a task over scdf dashboard by using deployer properties. I want to execute a shell command right after the pod creation, before the application initialization.

I looked at the [spring-cloud-dataflow-docs/configuration-kubernetes](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes), but I could not find a proper property. Is it possible to execute a shell command as I mentioned?

the version of spring-cloud-data-flow 2.5.0.

Thanks :)

**Comment by dturanski** [comment]
The recommended way to do this is using Lifecycle Hooks https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/.  I am working on an enhancement to expose `postStart` and `preStop` `exec` handlers. `httpGet` and `tcpSocket` will be deferred for now.

**Comment by canerkoseren** [comment]
Hi @dturanski,

I read the documentation you referenced and it seems that 'postStart' handler will fix my issue.

But there is one thing I wanted to ask. I am using 'shell' as entry point style.  Will I be able to use 'shell' entry point style with these hooks?

**Comment by dturanski** [comment]
> Hi @dturanski,
> 
> I read the documentation you referenced and it seems that 'postStart' handler will fix my issue.
> 
> But there is one thing I wanted to ask. I am using 'shell' as entry point style. Will I be able to use 'shell' entry point style with these hooks?

I expect it to work. LMK if you have any issues.
