### ISSUE TITLE
Could not retrieve log from k8s Job in SCDF when job finished

### ISSUE THREAD

**Issue by szopal** [spring-cloud/spring-cloud-deployer-kubernetes#468]
Hi, 

I think it is bug because when we used k8s POD event if POD was finished logs were available, but when we change to k8s Job when Job is finished we get message:

_Log could not be retrieved.  Verify that deployments are still available._

SCDF v.2.9.0

When I get logs by kubectl logs -f pod-id it works.

**Comment by jvalkeal** [comment]
Moved to k8s deployer.

Looking this and I think issue is there https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/57321c54fdd494b8534ddb7df0e0be3c7cd5fff0/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/KubernetesTaskLauncher.java#L198

**Comment by jvalkeal** [comment]
This was actually fixed in #463, closing in favour of #470.

**Comment by szopal** [comment]
Thanks. In which version SCDF this fix will be available?
