### ISSUE TITLE
Request to upgrade to k8s-client 5.x.x

### ISSUE THREAD

**Issue by vikulaggarwal** [spring-cloud/spring-cloud-deployer-kubernetes#493]
There have been several releases of k8s-client after 4.13.3. Please upgrade to k8s-client 5.x.x. It'll make it easier for consumers to avoid incompatibility issues while up-taking this libraryi.

I tried to use this library with k8s-client version 5.8.0, but there seems to be incompatibility with k8s-client 5.x.x.

**Comment by lgraf** [comment]
This is an issue when using `org.springframework.cloud:spring-cloud-dependencies` since as of the `2021.0.0`release it pulls in `io.fabric8:kubernetes-client:5.9`

**Comment by corneil** [comment]
2.8.0 does use fabric8:5.9

@onobc Do we need to do anything else?

**Comment by onobc** [comment]
@corneil thanks for verifying. @lgraf we will close this out w/ the understanding that it is fixed in 2.8.0 release. Feel free to re-open if you find otherwise. Thanks for the report.
