### ISSUE TITLE
Improve documentation on kuberenetes deployment properites

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-deployer-kubernetes#503]
Many of the kubernetes deployment property keys take a JSON string as their value.  This creates a bit of friction as all examples that are cut-n-pasted from k8s docs that are in YAML.  Volume mounts are a good example.  The JavaDoc for the deployer has many examples that should be surfaced in dataflow.spring.io, e.g. https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/blob/main/src/main/java/org/springframework/cloud/deployer/spi/kubernetes/DeploymentPropertiesResolver.java#L117

**Comment by corneil** [comment]
Updating reference documentation on Getting Started for Kubernetes to point to the Configuration - Kubernetes section which has information on the deployment properties.
